title: Sierra Foxtrot Oscar
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  Coding Adventures

author:
  name: "Stanley"
  email: "stanley.foerster@gmail.com"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sfo.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Theme settings
# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/).
# The remote_theme tag allows to use other (and more updated) themes hosted on GitHub.
remote_theme: jekyll/minima
minima:
  skin: solarized
  social_links:
    - platform: github
      user_url: "https://github.com/sfo"
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/579698/stanley-f"
    - platform: google_scholar
      user_url: "https://scholar.google.de/citations?user=CTYAlZgAAAAJ"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/stanley-f/"
show_excerpts: true

header_pages:
  - about.md
  - cv.md
  - research.md

plugins:
  - jekyll-feed