version: '2.4'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '80:4000'
    command: bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000 --future
