[project]
name = "endurance-race-evaluation"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
]
